<?php

function friends_menu()
{
    $items = array();
    $friends = array("bob", "joe", "tom");
    foreach ($friends as $friend) {
        $items['friends/' . $friend] = array(
            'title' => "Hello $friend!",
            'page callback' => 'hi_friend',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
    }
    return $items;
}

function hi_friend()
{
    return '<p>You\'re still my friend!!!!!! :)))</p>';
}
